version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint

  pre_build:
    commands:
      - echo Pre-build phase...
      - python --version
      - echo Running pylint on the project files...
      - find expenseTracker -name "*.py" | xargs pylint

  build:
    commands:
      - echo Running tests...
      - python3 manage.py test
      - echo Applying migrations...
      - python3 manage.py migrate
      - echo Collecting static files...
      - python3 manage.py collectstatic --noinput

  post_build:
    commands:
      - echo Post-build phase completed successfully!

artifacts:
  files:
    - '**/*'
