# Generated by Django 4.2.19 on 2025-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
    ]
